### ISSUE TITLE
Corrupted package 2.13.0

### ISSUE THREAD

**Issue by PatrykPlewaOfficial** [crowdin/crowdin-api-client-dotnet#122]
The package in version [2.13.0](https://www.nuget.org/packages/Crowdin.Api/2.13.0) contains no DLL files inside. It's literally empty.

**Comment by andrii-bodnar** [comment]
Sorry for the inconvenience, there is some issue with our CI/CD pipeline probably

**Comment by innomaxx** [comment]
The `dotnet pack` command generates empty NuGet Package. Trying to fix it.

**Comment by innomaxx** [comment]
Hi @PatrykPlewaOfficial,

We had already published a new version **2.13.1** which should work. Please test it on your side and give us feedback. Thank you!

**Comment by PatrykPlewaOfficial** [comment]
Hi, thank you.
The package finally works 👍 .

However, I have discovered some very disturbing changes in the consequences of this PR #115, which made some methods and classes invisible now.

**These are breaking changes however no major version was bumped.**

For example, now it's impossible to send requests using methods like `SendGetRequest` or it's impossible to register any of the JSON converters like `DescriptionEnumConverter`.

I don't say it's terrible, since everyone can copy the code for the custom JSON converter however, it's quite an unpleasant change, that was sneaked in a form of a feature, but really is a breaking change.

**Comment by innomaxx** [comment]
@PatrykPlewaOfficial
Thanks for your remark. We would like explain why we had done this.

These components we hid from the public are fully internal and not designed for usage outside of the library. All the requests should be sent via *Executor classes and their methods (like **SourceFilesApiExecutor/AddFile**). Method `SendGetRequest` and similar (for POST/PUT/PATCH/DELETE requests) are designed to use only from executors.

The same approach applied to library's custom JSON converters and some other components that are also hidden now. If you need any of them for your code - we suggest just copy-paste the implementation. Also you would receive an ability to customize the implementation and not depend from the library one. 

Therefore, because these components are fully internal, and no "true" public API affected, **there is the reason why we bumped minor version rather than major**. We apologize that we hadn't left any comments for these internal components before, that they are not part of "true" Public API and can be hidden or even removed in the future.

Also we are open for suggestions about improvements. If there are extra questions left - let's discuss. However maybe it's would be better open an another issue for it.
