### ISSUE TITLE
Add the JavaScript File Export Options

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#189]
Crowdin recently added the ability to configure the export options for JavaScript files. This is a great feature, but it's not yet supported by the API Client.

- `exportPattern` - string, File export pattern. Defines file name and path in resulting translations bundle.
- `exportQuotes` - string enum `single` or `double`. Defines quotes to be used in resulting translations bundle.

The new options need to be added to this API Client.

**API Reference:**

- [Add File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.post)
- [Edit File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.patch)
- [Get File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.get)

**Comment by Riju-bak** [comment]
@andrii-bodnar Can I take this up?

**Comment by andrii-bodnar** [comment]
@Riju-bak sure, thank you!

**Comment by Riju-bak** [comment]
@andrii-bodnar I have a question. So let's say a user is trying to add file with the following payload (say the user wants double quotes)
```
{
            "storageId": 1,
            "name": "fooFile.js",
            "branchId": 34,
            "directoryId": 4,
            "title": "Foo File",
            "type": "js",
            "exportOptions": {
                "exportPattern": "/files/fooFile.js",
                "exportQuotes": "DOUBLE"
            }
}
```

So in this payload, should "exportQuotes" be "double" or "DOUBLE" ? 

I'm asking because the description of `exportQuotes` enum elements are needed to be set appropriately for it to work. Otherwise crowdin's api might not understand the payload.
