### ISSUE TITLE
Apply Pre-Translation API: add labels support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#195]
Crowdin has recently added a possibility to Pre-Translate strings by labels. However, the new parameters are not supported in this API client.

The new `labelIds` and `excludeLabelIds` parameters should be added to the "Apply Pre-Translation" method in this API client.

**API Reference:**

- [Apply Pre-Translation](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.pre-translations.post)
- [Pre-Translation Status](https://developer.crowdin.com/enterprise/api/v2/#tag/Translations/paths/~1projects~1{projectId}~1pre-translations~1{preTranslationId}/get) (The `attributes` field now contains the new fields as well)

**Comment by Riju-bak** [comment]
@andrii-bodnar 
I have created a draft PR for now since the response-schema in API reference for [Pre-Translation-Status](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.pre-translations.get) doesn't contain the `labelIds` and `excludeLabelIds` parameters within the `attributes` field.  

Is the doc yet to be updated? Just want to be sure.

**Comment by andrii-bodnar** [comment]
@Riju-bak thanks for pointing this out!

I just checked it with Postman and the new fields are presented in the response. It seems that the documentation response sample hasn't been updated for this method, already passed it to the team.

![image](https://github.com/crowdin/crowdin-api-client-dotnet/assets/29282228/f109846c-e9c5-464a-bce7-fdf4d1d7359f)

**Comment by Riju-bak** [comment]
Got it. 
Switched the PR from draft to "ready for review".
