### ISSUE TITLE
Applications API support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#197]
Crowdin has recently added new endpoints for managing custom applications. Support for these endpoints is missing in this Crowdin API client.

We need to add support for the following endpoints:

- [Get Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.get)
- [Update or Restore Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.put)
- [Add Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.post)
- [Delete Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.delete)
- [Edit Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.patch)

**Comment by Riju-bak** [comment]
@andrii-bodnar Can I take this up?

**Comment by andrii-bodnar** [comment]
@Riju-bak sure, thanks a lot! 🚀

**Comment by Riju-bak** [comment]
The reference doesn't mention what fields the response data must contain. 
Also, it isn't clear what the acceptable string values of applicationIdentifier and path must be.

**Comment by andrii-bodnar** [comment]
@Riju-bak application - is a type of web application hosted on a separate domain that can be installed in Crowdin like a plugin.

Each application has its own identifier (`applicationIdentifier`) - it can be any string identifier. It is defined by the application itself. `path` is an endpoint implemented in the app.

For example - we have a Video Preview app that defines its own API - https://video-preview.awesome-crowdin.com/manifest.json. In this case - the identifier would be `preview-video` and `path` - `/configure`.

The `data` in this API can be any JSON object. Each application defines what payload it accepts for its endpoints.

**Comment by Riju-bak** [comment]
@andrii-bodnar @innomaxx Since each application defines what payload it accepts, to Edit Application Data in `crowdin-api-client-dotnet` we must send a patch request with a body of type `object` to make it generic.

However, note that the [SendPatchRequestMethod](https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/src/Crowdin.Api/CrowdinApiClient.cs#L248) inside `CrowdinApiClient.cs` requires the payload to be of type `IEnumerable<PatchEntry>`. This won't work for all applications.

Of course we can just change the payload type to `object`, but before doing that, could either of you confirm whether or not it won't break the client's ability to send PATCH requests. I can't say for sure, since I don't have access to the DB and/or any integration tests.

**Comment by innomaxx** [comment]
@Riju-bak we can add extra overload for method `SendPatchRequest` (or create entirely new method like `SendRawPatchRequest`) that accepts raw `System.Object` as parameter instead of collection of patches. We use the same approach with method `SendDeleteRequest_FullResult`

**Comment by Riju-bak** [comment]
@andrii-bodnar PR is now ready to review
